default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ecommerce_scraper_development

test:
  <<: *default
  database: ecommerce_scraper_test

production:
  <<: *default
  database: ecommerce_scraper_production
