source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  gem "brakeman", require: false

  gem "rubocop-rails-omakase", require: false
end

gem "nokogiri"
gem "httparty"
gem "sidekiq"
gem "redis"
gem "rspec-rails"
gem "rack-cors", "~> 2.0"
gem "active_model_serializers", "~> 0.10.15"
gem "kaminari", "~> 1.2"
gem "pry"